spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          #search-locations: file:/deploy/ai-open-platform/aop-config/config/shared/
  profiles:
    active: native

server:
  port: 8888