server:
  port: 8040
#turbine:
  #stream:
    #port: 8041
  
product:
  filter:
    enable: false
    
netflix:
  atlas:
    uri: http://localhost:7102/api/v1/publish
    
admin:
  server:
    username: admin
    password: admin
    userrole: ADMIN
    
spring:
  profiles:
    active:
      - insecure
  #boot:
    #admin:
      #routes:
        #endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      #turbine:
        #clusters: default
        #location: http://monitor:${turbine.stream.port}
        
---
spring:
  profiles: insecure

security:
  basic:
    enabled: false