spring:
  datasource:
    url: jdbc:mysql://192.168.123.12:3306/ai-open-plat?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update

server:
  context-path: /content
  port: 8000
  
management:
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
